### ISSUE TITLE
Invalid host defined options

### ISSUE THREAD

**Issue by leviluo** [alvarotrigo/nuxt-fullpage#14]
run with error，
![Uploading 截屏2024-04-15 16.16.23.png…]()

**Comment by leviluo** [comment]
error
![Uploading 截屏2024-04-15 16.13.23.png…]()
？？？

**Comment by leviluo** [comment]
FATAL  Invalid host defined options                                                                                                                                       16:11:36

  at module.exports (node_modules/.store/@fullpage+nuxt-fullpage@0.2.5/node_modules/@fullpage/nuxt-fullpage/dist/module.cjs:2:3)
  at ModuleContainer.addModule (node_modules/@nuxt/core/dist/core.js:239:34)
  at node_modules/@nuxt/utils/dist/utils.js:639:43
  at async ModuleContainer.ready (node_modules/@nuxt/core/dist/core.js:55:5)
  at async Nuxt._init (node_modules/@nuxt/core/dist/core.js:478:5)

**Comment by alvarotrigo** [comment]
I can't see the pictures.

And I can't reproduce the issue on [the example](https://github.com/alvarotrigo/nuxt-fullpage?tab=readme-ov-file#example).
