### ISSUE TITLE
Error on npm run dev

### ISSUE THREAD

**Issue by alvarotrigo** [alvarotrigo/nuxt-fullpage#8]
Executing `npm run dev` on the latest version throws this warning:

```
[Vue warn]: Failed to resolve component: full-page
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
``` 

I'm trying to update the vue-fullpage.js dependency to its latest version but not sure if I'm missing anything.
Any idea @JonathanSchndr ? 

Full message:
```sh
> @fullpage/nuxt-fullpage@0.2.4 dev:build
> nuxi build playground

Nuxt CLI v3.0.0-rc.3                                                                                                                       13:41:03

 WARN  Browserslist: caniuse-lite is outdated. Please run:                                                                                 13:41:06
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating

ℹ Vite client warmed up in 927ms                                                                                                           13:41:07
ℹ Client built in 1465ms                                                                                                                   13:41:08
ℹ Building server...                                                                                                                       13:41:08
Nuxt CLI v3.0.0-rc.3                                                                                                                       13:41:17
                                                                                                                                           13:41:17
  > Local:    http://localhost:3000/ 
  > Network:  http://192.168.1.71:3000/
  > Network:  http://192.168.1.93:3000/


 WARN  Browserslist: caniuse-lite is outdated. Please run:                                                                                 13:41:21
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating

ℹ Vite server warmed up in 149ms                                                                                                           13:41:22
ℹ Vite client warmed up in 756ms                                                                                                           13:41:22
✔ Vite server built in 530ms                                                                                                               13:41:22
✔ Nitro built in 276 ms                                                                                                              nitro 13:41:22
[Vue warn]: Failed to resolve component: full-page
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
[nitro] [dev] [unhandledRejection] TypeError: Invalid value used as weak map key
    at WeakMap.set (<anonymous>)
    at normalizePropsOptions (/Users/myuser/Sites/nuxt-fullpage/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:3404:11)
    at createComponentInstance (/Users/myuser/Sites/nuxt-fullpage/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6900:23)
    at renderComponentVNode (/Users/myuser/Sites/nuxt-fullpage/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:197:22)
    at Module.ssrRenderComponent (/Users/myuser/Sites/nuxt-fullpage/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:629:12)
    at _sfc_ssrRender (file:///Users/myuser/Sites/nuxt-fullpage/playground/.nuxt/dist/server/server.mjs:3466:31)
    at renderComponentSubTree (/Users/myuser/Sites/nuxt-fullpage/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:269:13)
    at renderComponentVNode (/Users/myuser/Sites/nuxt-fullpage/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:214:16)
    at Module.ssrRenderComponent (/Users/myuser/Sites/nuxt-fullpage/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:629:12)
    at default (file:///Users/myuser/Sites/nuxt-fullpage/playground/.nuxt/dist/server/server.mjs:2644:37)
[Vue warn]: Failed to resolve component: full-page
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
[nitro] [dev] [unhandledRejection] TypeError: Invalid value used as weak map key
    at WeakMap.set (<anonymous>)
    at normalizePropsOptions (/Users/myuser/Sites/nuxt-fullpage/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:3404:11)
    at createComponentInstance (/Users/myuser/Sites/nuxt-fullpage/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6900:23)
    at renderComponentVNode (/Users/myuser/Sites/nuxt-fullpage/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:197:22)
    at Module.ssrRenderComponent (/Users/myuser/Sites/nuxt-fullpage/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:629:12)
    at _sfc_ssrRender (file:///Users/myuser/Sites/nuxt-fullpage/playground/.nuxt/dist/server/server.mjs:3466:31)
    at renderComponentSubTree (/Users/myuser/Sites/nuxt-fullpage/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:269:13)
    at renderComponentVNode (/Users/myuser/Sites/nuxt-fullpage/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:214:16)
    at Module.ssrRenderComponent (/Users/myuser/Sites/nuxt-fullpage/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:629:12)
    at default (file:///Users/myuser/Sites/nuxt-fullpage/playground/.nuxt/dist/server/server.mjs:2644:37)
```

**Comment by JonathanSchndr** [comment]
I think a lot has changed, also Vite is in a new version. My suggestion would be to update the Vue plugin and then update the nuxt module - in that order. this will solve the problem. for a quick fix, this could help in the nuxt config (not tested):
```
export default defineNuxtConfig({
  vue: {  
    compilerOptions: {
      isCustomElement: (tag) => ['full-page'].includes(tag),
    },
  }
})
```
However, this is only a workaround.

**Comment by alvarotrigo** [comment]
That was quick! :D 
Thanks!

I've tried both, your solution:

```js
import { defineNuxtConfig } from 'nuxt'
import FullPage from '..'

export default defineNuxtConfig({
  modules: [
    FullPage
  ],

  vue: {
      compilerOptions: {
        isCustomElement: (tag) => ['full-page'].includes(tag),
      },
  }
})

```

And the same one but adding another level vue.config.compilerOptions

```js
import { defineNuxtConfig } from 'nuxt'
import FullPage from '..'

export default defineNuxtConfig({
  modules: [
    FullPage
  ],

  vue: {
    config: {
      compilerOptions: {
        isCustomElement: (tag) => ['full-page'].includes(tag),
      },
    }
  }
})

```  

Same warning.

**Comment by JonathanSchndr** [comment]
Would have been too easy :D – If it's ok for you, I would schedule a comprehensive Vue and Nuxt update of both repos, slaying the issues!

**Comment by alvarotrigo** [comment]
😆 

> If it's ok for you, I would schedule a comprehensive Vue and Nuxt update of both repos, slaying the issues!

Sure! That'd be awesome!
I've just updated them to include the latest fullpage.js version, but I didn't touch anything else.

Thanks Jonathan!! 👍

**Comment by JonathanSchndr** [comment]
Fixed in release https://github.com/alvarotrigo/nuxt-fullpage/releases/tag/0.2.5

**Comment by alvarotrigo** [comment]
Thanks @JonathanSchndr !! 🙏
